# Generated by Django 4.0.4 on 2022-04-27 21:32

from django.db import migrations, models
import homesite.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=191)),
                ('image', models.ImageField(blank=True, null=True, upload_to=homesite.models.filepath)),
            ],
        ),
    ]
